### ISSUE TITLE
Elastic GPE issue

### ISSUE THREAD

**Issue by smickusGT** [STOR-i/GaussianProcesses.jl#165]
When I try and use the ElasticGPE function I get the following error: 
`ERROR: MethodError: \(::ElasticPDMats.ElasticPDMat{Float64,Array{Float64,2}}, ::ElasticArrays.ElasticArray{Float64,1,0,Array{Float64,1}}) is ambiguous. Candidates:
  \(A::AbstractArray{T,2} where T, B::Union{AbstractArray{T,2}, AbstractArray{T,1}} where T) in LinearAlgebra at C:\Users\spenc\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\LinearAlgebra\src\generic.jl:1103
  \(a::ElasticPDMats.ElasticPDMat, x::AbstractArray) in ElasticPDMats at C:\Users\spenc\.juliapro\JuliaPro_v1.4.1-1\packages\ElasticPDMats\t0wsV\src\ElasticPDMats.jl:244
Possible fix, define
  \(::ElasticPDMats.ElasticPDMat, ::Union{AbstractArray{T,2}, AbstractArray{T,1}} where T)` 

I am not sure how I can resolve this error.

**Comment by jbrea** [comment]
Thanks for reporting. With the patch release [0.2.2 of ElasticPDMats](https://github.com/jbrea/ElasticPDMats.jl) this should be fixed. Please update your package versions, e.g. with `]up` before testing.

**Comment by smickusGT** [comment]
I still have the error when I am using Julia v1.0.5-2 which the long term supported version.  Is it possible for this issue to be solved when using this version of Julia?

**Comment by jbrea** [comment]
For me it works in Julia v1.0.5. Did you update all package versions or test in a clean project?
